# This file was generated by GoReleaser. DO NOT EDIT.
cask "open-tv" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "28ee3a4d747f6f6b7a761c898fdbc9e61cc503e95b8f54c28f426e0f2b83efd6"
      url "https://github.com/gdberysan/open-tv/releases/download/v#{version}/open-tv_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b0956b66923bc4208a58b01dcfa0bf7e3e8a5c3655e5b211e3a4184b8937e28"
      url "https://github.com/gdberysan/open-tv/releases/download/v#{version}/open-tv_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dcd5ec631b1171835217765bb893ec247755f7f6b9d569f48f68ed601d404b91"
      url "https://github.com/gdberysan/open-tv/releases/download/v#{version}/open-tv_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2e878e95a219b7c759b45565533d4a3a7ddf0ec081b2e604573583211caef2d9"
      url "https://github.com/gdberysan/open-tv/releases/download/v#{version}/open-tv_#{version}_linux_amd64.tar.gz"
    end
  end

  name "open-tv"
  desc "Reproductor de televisión abierta (FTA): un solo binario, tus propias listas M3U."
  homepage "https://github.com/gdberysan/open-tv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "open-tv"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/open-tv"]
    end
  end

  # No zap stanza required
end
